### ISSUE TITLE
New Account Creation

### ISSUE THREAD

**Issue by codingmusician** [seregazhuk/php-pinterest-bot#224] opened 2016-12-08 22:08 UTC
I used this library to create a new account with, but I never did receive a confirmation email from Pinterest. Looking at the account, I couldn't see where I was supposed to confirm my email address.

Then, when I started using the library for that account, my account got shut down. Have you experienced this issue (not receiving the confirmation email)? Is there a way to prevent this from happening? I've tested on a Gmail account and an owned domain email account to see if it was Gmail only, but it's not.

**Comment by seregazhuk** [comment] 2016-12-10 08:02
Hi @codingmusician , Pinterest doesn't send confirmation emails on registration.
I've checked it also with Gmail and  domain email - no email after registration, even if your register in a browser, not with my library.
You account was blocked? Maybe your were too aggressive with creating pins, commenting or searching.

**Comment by codingmusician** [comment] 2016-12-10 18:25
Here is an example of what we get when we manually create a new account: https://gyazo.com/deb919cc622e396f2bfe555a15fe0c30

Pinterest sends out an email with a confirmation link. That email is not being received for some reason and I can't seem to figure out why. We weren't too aggressive with anything. We had just started to follow other pinners and then we got blocked. This has not happened with accounts that we created manually and that were confirmed.

**Comment by seregazhuk** [comment] 2016-12-10 19:38
I'm sorry, but I cannot reproduce it. When I create a new account, no email is sent to me. I'm automatically logged in. As an example, I've just now registered here, from 404 page:
http://joxi.ru/nAyb5b7sYgygvr
Very strange, maybe it depends on user country... I don't know.

**Comment by seregazhuk** [comment] 2016-12-10 20:06
Oh, I see the issue. I'll try to fix it tomorrow.

**Comment by seregazhuk** [comment] 2016-12-11 08:36
@codingmusician , done! Fixed in version 5.1.2

**Comment by codingmusician** [comment] 2016-12-11 22:50
Wonderful! Thank you!

**Comment by codingmusician** [comment] 2016-12-18 05:08
Hello, again. We've updated our library (which is excellent, by the way) and have noticed that we still are not receiving a confirmation email from Pinterest after we use the codebase to register a new user.

This is the code we are using:
$result = $bot->auth->registerBusiness($postedVar["email"], $postedVar["password"], $postedVar["name"]);

We can see that an account has been created. We can actually log in and use it to follow topics and update the profile image. When we try to add a pin, it immediately gets shut down.

We've waited over 30 minutes for the email to get sent to us, but it never arrives.

Is there a trick that we are missing to creating an account without it getting shut down?

**Comment by codingmusician** [comment] 2016-12-18 05:30
We just switched to using the plain registration (non-business) and now we receive the emails. This call, for some reason, does not generate a confirmation email:
$bot->auth->registerBusiness('youremail@gmail.com', 'password', 'BusinessName');

**Comment by seregazhuk** [comment] 2016-12-18 19:14
Hi, @codingmusician 
Yes, I know this issue with business accounts. I'm working on it. I'll let you know when it will be fixed.

**Comment by seregazhuk** [comment] 2016-12-31 13:16
@codingmusician fixed receiving confirmation email after business account registration in version 5.1.7

**Closed** 2017-01-10 04:18 UTC
