### ISSUE TITLE
$bot->user->profile() not work

### ISSUE THREAD

**Issue by huuvu1109** [seregazhuk/php-pinterest-bot#198] opened 2016-10-23 05:44 UTC
Hi @seregazhuk ,

It seems that $bot->user->profile() is not work in the current version. Can you please fix it!

Thanks,

**Comment by seregazhuk** [comment] 2016-10-23 09:29
Hi @huuvu1109 ,
Fixed!

**Comment by huuvu1109** [comment] 2016-10-24 13:09
I works now. Thanks!

**Comment by seregazhuk** [comment] 2016-10-24 17:38
@huuvu1109 please update again. In the latest version, `update` method was fixed, but any pagination (search, followers, feeds and so on) has been broken. 
It is fixed in 4.13.3

**Comment by huuvu1109** [comment] 2016-11-12 16:56
Hi @seregazhuk ,

It seems that $categories = $bot->interests->main(); not works anymore. Can you plz check.

Also, I think it is more clear if you can update $bot->user->login('mypinterestlogin', 'mypinterestpassword'); in the Quick Start for consistency.

Thanks,

**Comment by seregazhuk** [comment] 2016-11-12 18:25
Hi, @huuvu1109 
Oh, thank you, I didn't notice, that quick start section is outdated! Thank you!

I've tried main categories and it works:
```php
$bot = PinterestBot::create();
$bot->auth->login('login', 'pass');

print_r($bot->interests->main());
print_r($bot->getLastError());

/*
Array
(
    [0] => Array
        (
            [images] => Array
                (
                    [45x] => Array
                        (
                            [url] => https://s-media-cache-ak0.pinimg.com/categories/architecture-1384730671-45x.jpg
                            [width] => 45
                            [height] => 45
                        )

                )

            [category_type] => main
            [type] => category
            [name] => Архитектура
            [key] => architecture
        )

    [1] => Array
        (
            [images] => Array
                (
                    [45x] => Array
                        (
                            [url] => https://s-media-cache-ak0.pinimg.com/categories/technology-1384730521-45x.jpg
                            [width] => 45
                            [height] => 45
                        )

                )

            [category_type] => main
            [type] => category
            [name] => Гаджеты
            [key] => technology
        )
        ...
*/
```

What is your output, or you get some errors?

**Comment by huuvu1109** [comment] 2016-11-12 18:38
Thanks @seregazhuk , I just check again and the reason is that I use an old password and it can not login ==> $bot->interests->main() return nothing. I don't realize this because the bot return nothing when it can not login. I think it is better if you still keep to return an exception if the Login not successful as before.

**Comment by seregazhuk** [comment] 2016-11-12 18:54
The bot should return `true` or `false` from `login()` method. I don't think it is a good idea to throw an exception at login. Maybe it is better to check the returned value, than to catch an exception. What was returned in your case?

**Comment by huuvu1109** [comment] 2016-11-12 18:58
Hi @seregazhuk ,
I see. I didn't realize that the bot return true, false because I just look at Quick Start. Everything is ok now. Thanks!

**Comment by huuvu1109** [comment] 2016-11-26 05:38
Hi @seregazhuk ,

Currently, for User Settings, it is possible to change the settings for : last_name, first_name, username, about, location, website_url and profile_image. Can you please also add "country" to the supported options?

**Comment by seregazhuk** [comment] 2016-11-26 06:39
Hi @huuvu1109 , It is not documented, but it works. Just pass `country` with iso2 code like this:

```php
$bot->user->profile(['country' => 'DE']);
```

I'll add it to the docs.

**Comment by huuvu1109** [comment] 2016-11-29 05:53
got it. Thanks!

**Comment by huuvu1109** [comment] 2017-03-11 08:40
Hi @seregazhuk ,

Can you please check if the follow function : $bot->pinners->follow still work? It seems that something wrong, when I use this function, the account is immediately suspended.

Thanks,

**Comment by seregazhuk** [comment] 2017-03-11 09:17
@huuvu1109 Hi, no, it still works fine, I've just checked it.
Maybe the user, you try to follow, complained about you.

**Comment by huuvu1109** [comment] 2017-03-11 21:10
Hi @seregazhuk ,

Thanks for your quick reply. It is really weird, something like Pinterest have a trap on the follow function to suspend accounts. After your comments, I tried to follow my own account to ensure there are no complaints, it is still suspended immediately after following. Then, I tried to change the IP, it is still died. Then, I used the account which have created a long time, it is died again. I'm using the newest version.

**Comment by seregazhuk** [comment] 2017-03-12 07:52
Hmm, how can I reproduce this issue? Does it happen only with your current accounts? If you create a new one and try to follow? What are your steps? Simply login and then follow, or maybe such follow behaviour is a side effect of something else?

**Comment by huuvu1109** [comment] 2017-03-13 05:57
I think I know the problem now.  I have tested it carefully. I use the account created by your bot, follow by the code, it dies. If I use another account created by your bot, follow by hand , it still die.  However, I tried to create a new account by hands, then, it is ok to use the function to follow, by code or by hand. So, I think there are some problem in the registration function of the bot.  One possible reason is when you register by hand, you must follow several topics immediately. However, by the bot, we can create the accounts without following any boards. I think you can check this.

**Comment by huuvu1109** [comment] 2017-03-13 06:13
oh, I just detect that I used the old version to create the Accounts and it leads to Suspended when follow. I just update the newest version, use newest version to create the accounts, and it works ok to follow other accounts.

**Comment by seregazhuk** [comment] 2017-03-13 11:07
I see, there was an issue with registrations a month ago. I close this issue. Try to follow updates)

**Closed by seregazhuk** 2017-03-13 11:07 UTC

**Comment by huuvu1109** [comment] 2017-03-25 07:50
Hi @seregazhuk ,

When you access to a pin without logging into your account, Pinterest not only show you the Pin you want to access, but also recommend a list of Pins which are similar to your pin. For example, let open the incognito window, and open this url: https://www.pinterest.com/pin/83527768070255703/ , then, you can see the result as the below figure:

![image](https://cloud.githubusercontent.com/assets/9253443/24320569/ff954382-1137-11e7-8211-53d4894f95d4.png)


Can you plz add one more feature to have these information. I have tried to use $info = $bot->pins->info() without logging in to account, but it seems that it doesn't work.

Thanks!

**Comment by seregazhuk** [comment] 2017-03-25 08:40
@huuvu1109 Hi!
This feature is already implemented. You can use it also when you are logged in. Try this:

```
Get related pins for current pin (returns Pagination object):

foreach($bot->pins->related($pinId) as $pin) {
	//...
}

// or get all of them at once as an array
$relatedPins = $bot->pins->related($pinId)->toArray();
```

**Comment by huuvu1109** [comment] 2017-03-25 09:00
Hi @seregazhuk ,

Thanks for your quick reply. I just  try to use $bot->pins->related($pinId) . And it works, it returns the related pins.  But can not get the "explore" text like in the returned result like  in the following figure (in the red rectangle). Is it possible to get this also? 


![image](https://cloud.githubusercontent.com/assets/9253443/24320982/9cd4905e-1141-11e7-9229-1db23538a7e3.png)

**Comment by seregazhuk** [comment] 2017-03-25 10:28
Fixed in 2.5.6
Yes, you should be not logged in to use this feature. Data, you are looking for is placed in `pin_join` array:

```php
$related = $bot->pins->related('83527768070255703'); 
foreach ($related as $pin) {
    if($pin['id'] == 355784439289886021) {
        print_r($pin['pin_join']); die();
    }
}
```

**Comment by huuvu1109** [comment] 2017-03-25 12:05
Hi @seregazhuk ,

Have you submitted the code yet? I just update the code and try again but there are still no "pin_join" results.

**Comment by seregazhuk** [comment] 2017-03-25 12:21
Oh, @huuvu1109 sorry, I've published wrong release number. Version 5.2.6 is actual. Try to update now.

**Comment by huuvu1109** [comment] 2017-03-26 11:32
Hi @seregazhuk ,

The date "pin_join " works fine now. I have one more question.  Can you also support to add the Sex (Male, Female) when creating accounts. When I create by hands, we have this option. So I think you should also support this to make it like normal person instead of a bot.

**Comment by seregazhuk** [comment] 2017-03-27 10:48
Yes, @huuvu1109 
I'm working on it. I don't like this ugly `register` method as it is now. It accepts 5 arguments, and you should remember their order. That first comes email, then password, then name, and so on. 

I am going to rewrite it and create a fluent interface, something like this:

```php
$bot->auth
    ->setName('name')
    ->setPassword('pass')
    ->setAge(30)
    ->setMaleGender()
   ->register();
```
So you can chain these call and there is no need to remember all of these arguments and their order.

**Comment by huuvu1109** [comment] 2017-03-27 17:42
Thanks, it's nice. Currently, it has 5 arguments, and also if you support "Gender" , so it will be 6 arguments:

**Comment by huuvu1109** [comment] 2017-03-27 17:46
Hi @seregazhuk ,

I just list the arguments again: 

1) 'youremail@gmail.com',
2)  'password', 
3) 'Name' -> it is nice now, but it can be more natural if it is separated to: First Name + Last Name like registering by hand.
4) Country:
5) Age: 
6) Gender

**Comment by seregazhuk** [comment] 2017-04-02 15:22
Hi, @huuvu1109 
It's done! In version 5.2.7 you can use *form objects* for registration and change profile settings. These classes have a fluent interface, so there is no need to remember all the parameters names and their order. Only set those values, that you need.  Of course, the old version also still works, so nothing will be broken after update.

## Registration:

```php
use seregazhuk\PinterestBot\Api\Forms\Registration;

$registration = new Registration('youremail@gmail.com', 'password', 'name');
$registration
    ->setAge(30)
    ->setCountry('DE')
    ->setMaleGender(); // ->setFemaleGender()

$bot->auth->register($registration);
```

the same with business registration:

```php
use seregazhuk\PinterestBot\Api\Forms\Registration;

$registration = new Registration('youremail@gmail.com', 'password', 'name');
$registration
    ->setAge(30)
    ->setCountry('DE')
    ->setMaleGender()
    ->setSite('http://yoursite.com');

$bot->auth->registerBusiness($registration);
```


## Change profile. 
To update profile you need to setup `Profile` form object. It has following methods:
 - `setLastName()`,
 - `setFirstName()`,
 - `setUserName()`,
 - `setAbout()`,
 - `setLocation()`,
 - `setWebsiteUrl()`,
 - `setCountry()` (ISO2 code)
 - `setImage()`:
```php
use seregazhuk\PinterestBot\Api\Forms\Profile

$profileForm = (new Profile())
            ->setFirstName('John')
            ->setLastName('Doe')
            ->setAbout('My bio')
            ->setCountry('UK');
$bot->user->profile($profileForm);
```

You can change your profile avatar by using `setImage()` method and a path to your image:
```php
use seregazhuk\PinterestBot\Api\Forms\Profile

$profileForm = (new Profile())->setImage($pathToFile);
$bot->user->profile($profileForm);
```

**Comment by huuvu1109** [comment] 2017-04-02 17:44
Hi @seregazhuk. It's very nice. Thanks!

**Comment by huuvu1109** [comment] 2017-04-08 10:36
Hi @seregazhuk ,

When we already logged in, Pinterest allows us to discover trending pins based on topics by using this link: https://www.pinterest.com/discover/ .  Can you plz also support to get these trending pins (by topics)? 

![image](https://cloud.githubusercontent.com/assets/9253443/24828160/98d4f982-1c57-11e7-99a3-36a5ff292252.png)

**Comment by seregazhuk** [comment] 2017-04-09 07:43
Hi, @huuvu1109 
Get version 5.3.0 and then use like this.

Get trending pins for a specific topic from http://pinterest.com/discover page. Uses topic id, that can be received from `$bot->topics->explore()` method (returns [Pagination](#pagination) object):

```php

$trendingTopics = $bot->topics->explore();
$firstTopicId = $trendingTopics[0]['id'];

$pins = $bot->pins->explore($firstTopicId)->toArray();
```

**Comment by huuvu1109** [comment] 2017-04-10 06:37
thanks a lot @seregazhuk

**Comment by huuvu1109** [comment] 2017-04-14 09:03
Hi @seregazhuk ,

It seems that there are some errors with the Registration again. I tried the new code and it not works. Can you plz check again.Thanks!



// You may need to amend this path to locate composer's autoloader
require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;
use seregazhuk\PinterestBot\Api\Forms\Registration;

$email = "askdksldkdkslsfsfs@gmail.com";
$pass = "abcdef123456789";
$fullName = "DDDDDD AAAA";
$iNumberOfAge = 80;


$bot = PinterestBot::create();

$registration = new Registration($email, $pass, $fullName);
$registration
    ->setAge(30)
    ->setCountry('DE')
    ->setMaleGender(); // ->setFemaleGender()

$bot->auth->register($registration);

**Comment by seregazhuk** [comment] 2017-04-14 09:28
Hi @huuvu1109 , thank you for your feedback! Yes, something is broken. I will try to fix it today/tomorrow.

**Comment by seregazhuk** [comment] 2017-04-14 09:51
@huuvu1109 done! get the latest version v5.3.1

**Comment by huuvu1109** [comment] 2017-04-14 10:08
@seregazhuk   It works well now. Thanks a lot for your quick fix.

**Comment by huuvu1109** [comment] 2017-04-15 07:39
Hi @seregazhuk ,

I see that Pinterest usually send us some suggestions by emails like the following figure:

![image](https://cloud.githubusercontent.com/assets/9253443/25061774/d7b826d6-21bd-11e7-89a2-913b6b7b4496.png)


In the figure, when we click on the board, it will open the board with link like the following. 


https://post.pinterest.com/f/a/opaJ9B5LR61bW8zRqonoOA~~/AAAAAQA~/RgRazNPkP0EIASxlZE8mXZ1XCXBpbnRlcmVzdFgEAAAAAEgmUkVDT01NRU5EQVRJT05TX0RJR0VTVF9CT0FSRFNfRkFMTEJBQ0tCCgAE5E7qWA09eoZSE2h1dXZ1MTk4eEB5YWhvby5jb20JUQQAAAAAhM4BaHR0cHM6Ly93d3cucGludGVyZXN0LmNvbS9zZWN1cmUvYXV0b2xvZ2luLz9vZD1sQTM1TnNtTElkRTFwUHhuNFhnTVUlMkZzeXNmT3RyS3hZcHprREV2bVJiYnZvUHI3TSUyRkhLaHV1ejBKSmw5Q2Q4Q0MyTzFnNlNTWDZnUiUwQVVacU5wOFM1RE5xdlBIVVhnZmRqVUpUMUElMkJ1aFBwM1hreFMyQjRwVERGVVNWQVg3VURtTUhZMjFoc2NpNVVGVW9HcHdmWnUlMkZzMVZIJTBBY24lMkJXdjklMkYwSlN0JTJCWXdGaDVQcyUzRCUwQSZ1c2VyX2lkPU16VTVOVGcwTkRnNE9UQTJOREV6TVRRNCUwQSZuZXh0PSUyRmFic2l0diUyRnRhdG9vJTJGJTNGdXRtX2NhbXBhaWduJTNEcmRib2FyZHNmJTI2ZV90JTNEM2RiZTQ0ZGM4MDZhNGE0NjliOTI3ODg2ODI4MzhkNWMlMjZ1dG1fY29udGVudCUzRDgyMzMxNDQ0NDMxNzY2MDMxMiUyNnV0bV9zb3VyY2UlM0QzMSUyNnV0bV90ZXJtJTNEMSUyNnV0bV9tZWRpdW0lM0QyMDA0R1V7InUiOiIzNTk1ODQ0ODg5MDY0MTMxNDgiLCJiaW5kaW5nIjoiZXhwbG9yZSIsInQiOiIzZGJlNDRkYzgwNmE0YTQ2OWI5Mjc4ODY4MjgzOGQ1YyJ9


Is it possible to support this action  also? I mean to simulate the "click" action from the email. I think it is something like to support the bot to send "GET" or "POST" requests:

For example, after loggined,
$bot->auth->login('mypinterestlogin', 'mypinterestpassword', false);

then,the  $bot can  send  two kinds of requests:

$bot->sendGetRequest("link", arrayOfGetParameters()); 
$bot->sendPostRequest("link",arrayOfPostParameters()); 

Thanks,

**Comment by seregazhuk** [comment] 2017-04-15 10:23
Hi, @huuvu1109 
To "click" a link you can use something like `$bot->user->visitPage($url)`. But it will only visit this page, you won't be able to get any data from it.
The bot has these `get` and `post` methods, by they are protected and hidden from the client code. There is often no need to make a post request because you need to find out appropriate request data, it's format and many other details. There is often a more abstract action (edit profile, create a comment). 
I'll add `$bot->user->visitPage($url)` to the documentation, as it may be useful for "clicking" URLs, but I don't see and valid reason to add something like `sendPostRequest` to public API.

**Comment by huuvu1109** [comment] 2017-04-15 10:28
Hi @seregazhuk , 

I see, I think visitPage($url) is enough for clicking URLs. Thanks!

**Comment by huuvu1109** [comment] 2017-06-11 10:48
Hi @seregazhuk , it seems that $info = $bot->getClientInfo(true); not work in the current version if we use Socks $bot->getHttpClient()->useSocksProxy(ip, '22', 'user:pass'); . Can you please fix this. Thanks!

**Comment by seregazhuk** [comment] 2017-06-11 17:48
Hi @huuvu1109 I think it is the issue with your proxy, not with the library. Does it work without proxy? When using this proxy all other methods work?

**Comment by huuvu1109** [comment] 2017-06-16 15:20
I checked it, @seregazhuk . The problem comes from my proxy. THanks!

**Comment by huuvu1109** [comment] 2017-07-08 10:13
Hi @seregazhuk ,

The functions $profile = $bot->user->profile();, $username = $bot->user->username(); $userId = $bot->user->id(); doesn't work in the current version. Can you please fix this. Thanks!

**Comment by seregazhuk** [comment] 2017-07-08 14:54
Hi, @huuvu1109 I cannot reproduce it. To me everything works fine. Can you show me your code. And what returns `$bot->getLastError()`?

**Comment by huuvu1109** [comment] 2017-07-09 02:47
Note that I create account successfully, can follow the topics, but when I request for username and userID, it returns empty.

**Comment by seregazhuk** [comment] 2017-07-09 06:34
Still can't reproduce it.  Here Is my code.

```php
$bot = PinterestBot::create();
$bot->auth->register('yiyi@garage46.com', 'secret', 'mike');
$bot->auth->login('yiyi@garage46.com', 'secret', 'mike');

$bot->topics->follow('content-marketing');

var_dump($bot->user->id());
var_dump($bot->getLastError());
```


May be you got banned?

**Comment by huuvu1109** [comment] 2017-07-09 07:47
Hi @seregazhuk ,

This is the output of your code with changes on emails to create new accounts:

string(18) "854347129219492393"
NULL

Do you use composer require seregazhuk/pinterest-bot  to get the newest version? I tested on the newest version.

**Comment by seregazhuk** [comment] 2017-07-09 08:31
To get the latest version you should use `composer update`. I still can not reproduce your bug.

**Comment by huuvu1109** [comment] 2017-07-09 09:24
Hi @seregazhuk ,

I know where is the error now, something wrong with the function $profileForm = (new Profile())->setImage("aaaa.jpg"); . 



1) For example, this code is fine:

$bot = PinterestBot::create();
$bot->auth->register('yiyi@garage46.com', 'secret', 'mike');
$bot->auth->login('yiyi@garage46.com', 'secret', 'mike');

$bot->topics->follow('content-marketing');

var_dump($bot->user->id());
var_dump($bot->getLastError());

$profileForm = (new Profile())->setImage("aaaa.jpg");
$bot->user->profile($profileForm);


2) But this code can NOT get the userID, the different is from calling setImg before calling $bot->user->id()

$bot = PinterestBot::create();
$bot->auth->register('yiyi@garage46.com', 'secret', 'mike');
$bot->auth->login('yiyi@garage46.com', 'secret', 'mike');

$bot->topics->follow('content-marketing');


$profileForm = (new Profile())->setImage("aaaa.jpg");
$bot->user->profile($profileForm);

var_dump($bot->user->id());
var_dump($bot->getLastError());

**Comment by seregazhuk** [comment] 2017-07-09 10:09
Thank you! I see the problem now. Tomorrow will be fixed.

**Comment by seregazhuk** [comment] 2017-07-10 14:20
@huuvu1109 Hi, I've published a new release with profile fix (5.5.1). Update, please.

**Comment by huuvu1109** [comment] 2017-07-22 22:13
Hi @seregazhuk , 

Pinterest has one feature which allow one pinner to share a pin on Facebook, Twitter, ... like the first figure . The shared content will contains a link to the shared Pin and allow other Pinners can vote the shared Pin (the second figure). Can the bot do this automatically? I mean to share a pin, get the shared link (created by Pinterest), and another account to use that link to vote. Thanks!


![image](https://user-images.githubusercontent.com/9253443/28494842-d4aa814e-6f3a-11e7-81fe-564aee79c0f8.png)

![image](https://user-images.githubusercontent.com/9253443/28494861-736f0de0-6f3b-11e7-9bb2-a5b5430f3b23.png)

**Comment by seregazhuk** [comment] 2017-07-24 15:45
Hi, @huuvu1109 
Yes, it is possible. Will be added in the future release

**Comment by seregazhuk** [comment] 2017-07-24 15:47
@huuvu1109 Can you please open an issue with the same description and pictures? 
It will be much easier for me to track the incoming feature requests. Now I have to look through the closed issues and scroll to the last comment :)

**Comment by huuvu1109** [comment] 2017-07-24 15:57
Got it @seregazhuk . Next time, I will create a new issue. Thanks!

**Comment by hsynucak** [comment] 2020-02-25 14:53
hello;
user registeration issue  please help me;
code : 
$registration = new Registration('candytaylor13@yahoo.com', '123456aab+-', 'volkan');
$registration
    ->setAge(30)
    ->setCountry('DE')
    ->setMaleGender()
    ->setSite('http://candytaylor13.com');

$return = $bot->auth->registerBusiness($registration);

error: string(19) "Invalid parameters."
